#!/usr/bin/env node
var program = require('commander');

program
  .version('0.1.0')
  .description("ubykuo-ci CLI interface");

program
  .command('init')
  .description('Add project to CI server from existing .ubykuo-ci config file.')
  .option("-C, --config_file <file>", "defaults to .ubykuo-ci", ".ubykuo-ci")
  .action(initCommand);

program
  .command('list')
  .description('List projects.')
  .action(listCommand);

program
  .command('ssh')
  .description('Get public key.')
  .action(listCommand);

program.parse(process.argv);

function initCommand(cmd) {
  console.log("reading %s file for this project", cmd.config_file);
}

function listCommand(cmd) {
  console.log("list projects");
}

